In [1]:
from PIL import Image
from pylab import *
import scipy.stats as st
import scipy.signal as sign
import numpy as np

file_path = '../resources/'
IMG1_NAME = 'img1.jpg'
IMG2_NAME = 'img2.jpg'


def create_grayscale_img(img_name):

    def transform_img(img_name):
        image = Image.open(file_path + img_name).convert('L')  # Открываем изображение и конвертируем в полутоновое

        return image

    image = transform_img(img_name)
    image.save(file_path + "grayscale_" + img_name)
    return image


def analize_img(image):
    hist_data = array(image).flatten()
    stat = {}

    stat.update([
        ('mean', np.mean(hist_data)),
        ('std', np.std(hist_data)),
        ('mode', st.mode(hist_data)[0][0]),
        ('median', np.median(hist_data))])

    return hist_data, stat


def img_histogram(image):

    def show_histogram(data, bins):
        figure()
        hist(data, bins)
        show()

    img_array = array(image).flatten()
    show_histogram(img_array, 26)


def img_correlation(img1, img2):
    x = np.array(img1)
    y = np.array(img2)

    return sign.correlate2d(x, y)

def hyp_check_ks(_dataset):
    print(st.kstest(_dataset, cdf='norm'))

def hyp_check_chi2(_dataset):
    chi2, p = st.chisquare(_dataset)
    msg = "Test Statistic: {}\np-value: {}"
    print(msg.format(chi2, p))

def main():
    image1 = create_grayscale_img(IMG1_NAME)
    image2 = create_grayscale_img(IMG2_NAME)

    img_histogram(image1)
    img_histogram(image2)

    hist1, hist_stat1 = analize_img(image1)
    hist2, hist_stat2 = analize_img(image2)

    print('Explore:')
    print("First image: ", hist_stat1)
    print("Second image: ", hist_stat2)

    print("Histogram correlation: ",
          np.corrcoef(
              np.asarray(hist1).flatten(),
              np.asarray(hist2).flatten()
          )[1, 0])

    print('Images` correlation', img_correlation(image1, image2))

    print('\nHypothesis:\n')
    hyp_check_chi2(hist1)
    hyp_check_chi2(hist2)

    hyp_check_ks(hist1)
    hyp_check_ks(hist2)


if __name__ == "__main__":
    main()

<Figure size 640x480 with 1 Axes>

<Figure size 640x480 with 1 Axes>

Explore:
First image:  {'mean': 91.7561, 'std': 43.2042730848466, 'mode': 70, 'median': 80.0}
Second image:  {'mean': 101.6791, 'std': 65.95577551048885, 'mode': 49, 'median': 70.0}
Histogram correlation:  0.3877845128026241
Images` correlation [[252 144  28 ... 191  20 238]
 [250 206 127 ... 140 125  70]
 [185  56 169 ...  45 235  79]
 ...
 [ 27 131 212 ...   6 231  18]
 [ 86 217 169 ...  51 235 204]
 [166  45 185 ...  11 186 217]]

Hypothesis:

Test Statistic: 203431.62065410364
p-value: 0.0
Test Statistic: 427832.69356141036
p-value: 0.0
KstestResult(statistic=0.9999999990134123, pvalue=0.0)
KstestResult(statistic=0.9989683287581669, pvalue=0.0)
